name: Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.10
        uses: actions/setup-node@v1
        with:
          node-version: 12.10
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Install now.sh
        run: sudo npm install -g --unsafe-perm now
      - name: Deploy Now
        run: cd ./dist/kaf-first-anniversary && now --prod -n kaf1th -t ${{secrets.ZEIT_TOKEN}}
