name: Test

on:
  push:
    branches:
    - dev

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.10
        uses: actions/setup-node@v1
        with:
          node-version: 12.10
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
